(define (list_cmp lst1 lst2)
  (cond ((null? lst1) #t)
        ((> (car lst1) (car lst2)) #t)
        ((< (car lst1) (car lst2)) #f)
        ((= (car lst1) (car lst2)) (list_cmp (cdr lst1) (cdr lst2)))
  )
)

(define (find_max lst max_lst curr_lst)
    (cond ((null? lst) 
            (cond ((> (length curr_lst) (length max_lst))
                    curr_lst
                )
                ((= (length curr_lst) (length max_lst))
                    (if (list_cmp max_lst curr_lst) max_lst
                        curr_lst
                    )
                )
                ((< (length curr_lst) (length max_lst))
                    max_lst
                )
            )
        )
        ((null? curr_lst) 
            (find_max (cdr lst) max_lst (cons (car lst) curr_lst))
        )
        ((> (car lst) (car curr_lst))
            (find_max (cdr lst) max_lst (cons (car lst) curr_lst))
        )
        ((not (> (car lst) (car curr_lst)))
            (cond ((> (length curr_lst) (length max_lst))
                    (find_max (cdr lst) curr_lst (list (car lst)))
                )
                ((= (length curr_lst) (length max_lst))
                    (if (list_cmp max_lst curr_lst) (find_max (cdr lst) max_lst (list (car lst)))
                        (find_max (cdr lst) curr_lst (list (car lst)))
                    )
                )
                ((< (length curr_lst) (length max_lst))
                    (find_max (cdr lst) max_lst (list (car lst)))
                )
            )
        )
    )
)

(define (max-decreasing-subsegment sequence)
  (find_max (reverse sequence) '() '())
)