(define (reverseDup lst)
    (append (reverse lst) (reverse lst))
)

(define (binpow a b)
    (cond ((= b 0) 1)
        ((even? b) (let ((x (binpow a (quotient b 2))))
                (* x x)
            )
        )
        (else 
            (let ((x (binpow a (quotient (- b 1) 2))))
                (* x x a)
            )
        )
    )
)

(define (fib n)
    (let loop((x 0) (y 1) (z n))
        (if(zero? z) x
            (loop y (+ y x) (- z 1))
        )
    )
)

(define (partition n lst)
    (let loop ( (x '()) (y '()) (z lst) )
        (cond ((null? z) (list x y))
            ((< (car z) n) (loop (append x (list (car z))) y (cdr z)))
            (else (loop x (append y (list (car z))) (cdr z)))
        )
    )
)

(define (permutation? lst1 lst2)
    (cond ((not (= (length lst1) (length lst2))) #f)
        ((and (null? lst1) (null? lst2))  #t)
        (else (permutation? (cdr lst1) (remove_ (car lst1) lst2)))
    )
)

(define (remove_ n lst)
    (let loop ( (x '()) (y lst) )
        (cond ((null? y) x)
            ((equal? (car y) n) (append x (cdr y)))
            (else (loop (append x (list (car y))) (cdr y)))
        )
    )
)